name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t  temperature_converter .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          
      - name: Push Docker image
        run: |
          docker tag  temperature_converter ${{ secrets.DOCKER_USERNAME }}/temperature_converter:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/temperature_converter:latest